#!/usr/bin/env bash

isRunning=false
workspaceId=$(docker-compose ps -q app)
if [[ -n "$workspaceId" ]] && docker ps -q --no-trunc | grep -q "${workspaceId}"; then
  isRunning=true
fi

start() {
  # Start existing service containers if they already exist; otherwise create them.
  docker-compose up -d
  isRunning=true
}

stop() {
  echo "Removing containers"
  docker-compose down --remove-orphans
  isRunning=false
}

build() {
  echo "Building..."
  docker-compose build --no-cache --force-rm
}

restart() {
  stop
  start
}

ssh() {
  if [[ "$isRunning" == false ]]; then
    start
  fi

  echo "Connecting to workspace"

  docker exec -it theapp_workspace bash
}

if [[ -n "$1" ]]; then
  command="$1"
  if [[ -n "$(type -t "${command}")" ]] && [[ "$(type -t "${command}")" == function ]]; then
    "$command" "${@:2}"
    exit
  else
    echo "Command not found"
    exit
  fi
fi
